# task file for redis role

- !facts
  {}

- !echo
  msg: "OS release detected={{ jet_os_release_id_like }}"

- !dnf
  package: redis
  with:
    cond: (eq jet_os_release_id_like "rhel fedora centos")

- !apt
  package: redis
  with:
    cond: (eq jet_os_release_id_like "debian")

- !template
  src: redis.conf.hb
  dest: /etc/redis/redis.conf
  attributes:
     owner: redis
     group: redis
     mode: 0o640
  and:
     notify: restart redis

- !sd_service
  service: redis
  started: true
  enabled: true

 
