- name: this is a demo of items loops
  groups: 
   - all

  defaults:

     a_list:
       - uno
       - dos
       - tres
     b_list:
       - { a: "one", b: 1 }
       - { a: "two", b: 2 }
     c_dict:
       a: "one"
       b: "two"
     d_dict:
       x: { a: "one", b: "{{ narf }}" }
       y: { a: "two", b: "3" }
  
     narf: "Narf!"
     fjord: "Fjord!!!"

  tasks:

   - !echo
     name: "looping over a basic list"
     msg: "{{ item }}"
     with:
        items: a_list

   - !echo
     name: "looping over a structured list"
     msg: "a={{ item.a }} b={{ item.b}}"
     with:
         items: b_list   

   - !echo
     name: "a dictionary passed as a variable"
     msg: "key={{ item.key }} value={{ item.value }}"
     with:
        items: c_dict
   
   - !echo
     name: "a dictionary passed as a variable (2)"
     msg: "key={{item.key}} a={{ item.value.a }} b={{ item.value.b}}"
     with:
         items: d_dict   

   - !echo
     name: "a list (not from a variable) that may contain templates"
     msg: "{{ item }}"
     with:
        items:
           - "" 
           - "{{ narf }}"
           - asdf
           - jkl
   
   - !echo
     name: "a dict (not from a variable) that may contain templates"
     msg: "key={{item.key}} value={{item.value}}"
     with:
         items:
            a: "{{ narf }}"
            b: "two"


          

